# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'done.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os
import subprocess as sp


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1078, 551)
        MainWindow.setStyleSheet("background-color:  #000000")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(530, 460, 531, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setEnabled(False)
        self.plainTextEdit.setGeometry(QtCore.QRect(50, 130, 441, 371))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background-color: gray;\n"
                                         "color: white;\n"
                                         "border-radius: 5px")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(550, 90, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #ffffff\n"
                                 "")
        self.label.setObjectName("label")
        self.consumerkey = QtWidgets.QLineEdit(self.centralwidget)
        self.consumerkey.setGeometry(QtCore.QRect(710, 90, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.consumerkey.setFont(font)
        self.consumerkey.setStyleSheet("background-color: #ffffff")
        self.consumerkey.setObjectName("consumerkey")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(520, 140, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #ffffff")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(610, 190, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #ffffff")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(570, 240, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #ffffff")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(600, 290, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #ffffff")
        self.label_5.setObjectName("label_5")
        self.consumersecret = QtWidgets.QLineEdit(self.centralwidget)
        self.consumersecret.setGeometry(QtCore.QRect(710, 140, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.consumersecret.setFont(font)
        self.consumersecret.setStyleSheet("background-color: #ffffff")
        self.consumersecret.setObjectName("consumersecret")
        self.accesstoken = QtWidgets.QLineEdit(self.centralwidget)
        self.accesstoken.setGeometry(QtCore.QRect(710, 190, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.accesstoken.setFont(font)
        self.accesstoken.setStyleSheet("background-color: #ffffff")
        self.accesstoken.setObjectName("accesstoken")
        self.accesstokensecret = QtWidgets.QLineEdit(self.centralwidget)
        self.accesstokensecret.setGeometry(QtCore.QRect(710, 240, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.accesstokensecret.setFont(font)
        self.accesstokensecret.setStyleSheet("background-color: #ffffff")
        self.accesstokensecret.setObjectName("accesstokensecret")
        self.keyword = QtWidgets.QLineEdit(self.centralwidget)
        self.keyword.setGeometry(QtCore.QRect(710, 290, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.keyword.setFont(font)
        self.keyword.setStyleSheet("background-color: #ffffff")
        self.keyword.setObjectName("keyword")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 10, 91, 91))
        self.label_6.setStyleSheet(
            "background-image: url(C:/Users/subhashish/PycharmProjects/twiPight/rsz_1percintellect.png)")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.livebtn = QtWidgets.QPushButton(self.centralwidget)
        self.livebtn.setGeometry(QtCore.QRect(570, 360, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.livebtn.setFont(font)
        self.livebtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.livebtn.setStyleSheet("background-color: #5FF5DD;\n"
                                   "border: 2px solid #008670\n"
                                   "")
        self.livebtn.setAutoDefault(False)
        self.livebtn.setDefault(True)
        self.livebtn.setObjectName("livebtn")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(800, 360, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("background-color: #5FF5DD;\n"
                                        "border: 2px solid #008670\n"
                                        "")
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setDefault(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(140, 30, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Humnst777 BlkCn BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setStyleSheet("COLOR: #ffffff;\n"
                                           "border: 2px solid #00B1DC;")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(420, 40, 61, 41))
        self.label_7.setStyleSheet("background-image: url(C:/Users/subhashish/PycharmProjects/twiPight/rsz_s.png)")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.ckerror = QtWidgets.QLabel(self.centralwidget)
        self.ckerror.setGeometry(QtCore.QRect(1050, 100, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ckerror.setFont(font)
        self.ckerror.setStyleSheet("color: red")
        self.ckerror.setText("")
        self.ckerror.setObjectName("ckerror")
        self.cserror = QtWidgets.QLabel(self.centralwidget)
        self.cserror.setGeometry(QtCore.QRect(1050, 150, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cserror.setFont(font)
        self.cserror.setStyleSheet("color: red")
        self.cserror.setText("")
        self.cserror.setObjectName("cserror")
        self.aterror = QtWidgets.QLabel(self.centralwidget)
        self.aterror.setGeometry(QtCore.QRect(1050, 200, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.aterror.setFont(font)
        self.aterror.setStyleSheet("color: red")
        self.aterror.setText("")
        self.aterror.setObjectName("aterror")
        self.atserror = QtWidgets.QLabel(self.centralwidget)
        self.atserror.setGeometry(QtCore.QRect(1050, 250, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.atserror.setFont(font)
        self.atserror.setStyleSheet("color: red")
        self.atserror.setText("")
        self.atserror.setObjectName("atserror")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(940, 300, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: red")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.logoutbnt = QtWidgets.QPushButton(self.centralwidget)
        self.logoutbnt.setGeometry(QtCore.QRect(990, 21, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.logoutbnt.setFont(font)
        self.logoutbnt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logoutbnt.setStyleSheet("background-color: gray;\n"
                                     "border: 2px solid #008670\n"
                                     "")
        self.logoutbnt.setAutoDefault(False)
        self.logoutbnt.setDefault(True)
        self.logoutbnt.setObjectName("logoutbnt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1078, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.livebtn.clicked.connect(self.run_live_analyzer)
        # self.pushButton_3.clicked.connect(self.run_historic_analyzer())
        self.logoutbnt.clicked.connect(self.logout_func)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def run_live_analyzer(self):
        ck = self.consumerkey.text()
        cs = self.consumersecret.text()
        at = self.accesstoken.text()
        ats = self.accesstokensecret.text()
        key = self.keyword.text()
        system = sp.call(['python','liveanalyzer.py',ck, cs, at, ats, key])

    def run_historic_analyzer(self):
        ck = self.consumerkey.text()
        cs = self.consumersecret.text()
        at = self.accesstoken.text()
        ats = self.accesstokensecret.text()
        key = self.keyword.text()
        system = sp.call(['python','historic_analyzer.py',ck, cs, at, ats, key])

    # def run_historic_analyzer(self):
    #     ck = self.consumerkey.text()
    #     cs = self.consumersecret.text()
    #     at = self.accesstoken.text()
    #     ats = self.accesstokensecret.text()
    #     key = self.keyword.text()
    #     system = sp.call(['python', 'historic_analyzer.py', ck, cs, at, ats, key])

    def logout_func(self):
        os.kill()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Percintellect | Analysis Visualizer"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "\n"
                                                                 "To access the percintellect software, get all the keys by logging in the Twitter Application Management Interface available on url - (https://apps.twitter.com/).\n"
                                                                 "\n"
                                                                 "Steps to follow :\n"
                                                                 "\n"
                                                                 "1. After logging in click the Create an App button on the top right corner.\n"
                                                                 "\n"
                                                                 "2. Fill Up all the details properly.\n"
                                                                 "\n"
                                                                 "3. Get to the panel named Keys and Access Tokens\n"
                                                                 "\n"
                                                                 "4. Copy all the keys one by one and paste it over the given space at left.\n"
                                                                 "\n"
                                                                 "5. Enter the proper keyword you want to Analyze the sentiments coming out by the people about.\n"
                                                                 ""))
        self.label.setText(_translate("MainWindow", "CONSUMER KEY (API KEY) :"))
        self.label_2.setText(_translate("MainWindow", "CONSUMER SECRET (API SECRET) :"))
        self.label_3.setText(_translate("MainWindow", "ACCESS TOKEN :"))
        self.label_4.setText(_translate("MainWindow", "ACCESS TOKEN SECRET:"))
        self.label_5.setText(_translate("MainWindow", "KEYWORD : - "))
        self.livebtn.setText(_translate("MainWindow", "LIVE Tweet Analysis"))
        self.pushButton_3.setText(_translate("MainWindow", "HISTORIC Tweet Analysis"))
        self.plainTextEdit_2.setPlainText(
            _translate("MainWindow", "            AI: LIVE + HIST                            SOCIOSENTIMENT ANALYZER"))
        self.logoutbnt.setText(_translate("MainWindow", "Logout"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
