# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'percintellect.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import done
import os
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.next = done.Ui_MainWindow()
        self.next_window = QtWidgets.QMainWindow()
        self.next.setupUi(self.next_window)

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 558)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setStyleSheet("background-color: #000000\n""")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 40, 471, 531))
        self.label.setStyleSheet(
            "background-image: url(C:/Users/subhashish/PycharmProjects/twiPight/percintellect.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.logemail = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logemail.setGeometry(QtCore.QRect(660, 90, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.logemail.setFont(font)
        self.logemail.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.logemail.setStyleSheet("background-color: #ffffff;\n""color: #000000\n""")
        self.logemail.setTabChangesFocus(True)
        self.logemail.setObjectName("logemail")
        self.loginbtn = QtWidgets.QPushButton(self.centralwidget)
        self.loginbtn.setGeometry(QtCore.QRect(740, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.loginbtn.setFont(font)
        self.loginbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginbtn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.loginbtn.setStyleSheet("background-color: #cccccc\n""")
        self.loginbtn.setObjectName("loginbtn")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setEnabled(True)
        self.line.setGeometry(QtCore.QRect(490, 25, 1, 511))
        self.line.setStyleSheet("background-color: #ffffff")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(629, 37, 3, 193))
        self.line_2.setStyleSheet("background-color:  #262626")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(961, 39, 3, 191))
        self.line_3.setStyleSheet("background-color:  #262626")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(630, 38, 331, 3))
        self.line_5.setStyleSheet("background-color:  #262626")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(630, 231, 332, 3))
        self.line_6.setStyleSheet("background-color:  #262626")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(740, 450, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("background-color: #cccccc\n""\n""")
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(961, 268, 3, 230))
        self.line_4.setStyleSheet("background-color:  #262626")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(629, 268, 3, 230))
        self.line_7.setStyleSheet("background-color:  #262626")
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(630, 267, 331, 3))
        self.line_8.setStyleSheet("background-color:  #262626")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(630, 499, 332, 3))
        self.line_9.setStyleSheet("background-color:  #262626")
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.logpass = QtWidgets.QLineEdit(self.centralwidget)
        self.logpass.setGeometry(QtCore.QRect(660, 130, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.logpass.setFont(font)
        self.logpass.setStyleSheet("background-color: #ffffff")
        self.logpass.setText("")
        self.logpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.logpass.setObjectName("logpass")
        self.signemail = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.signemail.setGeometry(QtCore.QRect(660, 320, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.signemail.setFont(font)
        self.signemail.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.signemail.setStyleSheet("background-color: #ffffff;\n""color: #000000\n""")
        self.signemail.setTabChangesFocus(True)
        self.signemail.setObjectName("signemail")
        self.signpass = QtWidgets.QLineEdit(self.centralwidget)
        self.signpass.setGeometry(QtCore.QRect(660, 360, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.signpass.setFont(font)
        self.signpass.setStyleSheet("background-color: #ffffff")
        self.signpass.setText("")
        self.signpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.signpass.setObjectName("signpass")
        self.signconfirmpass = QtWidgets.QLineEdit(self.centralwidget)
        self.signconfirmpass.setGeometry(QtCore.QRect(660, 400, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.signconfirmpass.setFont(font)
        self.signconfirmpass.setStyleSheet("background-color: #ffffff")
        self.signconfirmpass.setText("")
        self.signconfirmpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.signconfirmpass.setObjectName("signconfirmpass")
        self.loginerror = QtWidgets.QLabel(self.centralwidget)
        self.loginerror.setGeometry(QtCore.QRect(660, 70, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        self.loginerror.setFont(font)
        self.loginerror.setStyleSheet("color: red;")
        self.loginerror.setText("")
        self.loginerror.setObjectName("loginerror")
        self.signuperror = QtWidgets.QLabel(self.centralwidget)
        self.signuperror.setGeometry(QtCore.QRect(660, 300, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        self.signuperror.setFont(font)
        self.signuperror.setText("")
        self.signuperror.setObjectName("signuperror")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.loginbtn.clicked.connect(self.logging_validation)  ##############
        self.pushButton_2.clicked.connect(self.signing_Up)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def logging_validation(self):
        if self.logemail.toPlainText() == '' or self.logpass.text() == '':
            self.loginerror.setText('* Fields cannot be blank')
        else:
            self.loginerror.setText('')
            e = self.logemail.toPlainText()
            p = self.logpass.text()
            con = sqlite3.connect('precintellect.db')
            query=f"""SELECT * FROM user_info WHERE emailid = '{e}' AND password = '{p}'"""
            if con.execute(query).fetchall():
                self.logemail.setPlainText('')
                self.logpass.setText('')
                # os.system('python done.py')
                self.next_window.show()
            else:
                self.loginerror.setText('* Username or Password not found')

    def signing_Up(self):
        if self.signemail.toPlainText() == '' or self.signpass.text() == '' or self.signconfirmpass.text() == '':
            self.signuperror.setStyleSheet("color: red;")
            self.signuperror.setText('* Please provide all details to SignIn')
        elif self.signpass.text() != self.signconfirmpass.text():
            self.signuperror.setStyleSheet("color: red;")
            self.signuperror.setText("* Password doesn't match")
        else:
            e = self.signemail.toPlainText()
            p = self.signpass.text()

            con = sqlite3.connect('precintellect.db')
            query = f"insert into user_info values (null, '{e}', '{p}')"
            try:
                con.execute(query)
                con.commit()
                self.reset_func()
                self.signuperror.setStyleSheet("color: green;")
                self.signuperror.setText('You have been registered :)')
            except Exception as e:
                print(e)

    def reset_func(self):
        self.logemail.setPlainText('')
        self.logpass.setText('')
        self.loginerror.setText('')
        self.signemail.setPlainText('')
        self.signpass.setText('')
        self.signconfirmpass.setText('')
        self.signuperror.setText('')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Precintellect"))
        self.logemail.setPlaceholderText(_translate("MainWindow", "    Email-id"))
        self.loginbtn.setText(_translate("MainWindow", "LogIn"))
        self.pushButton_2.setText(_translate("MainWindow", "SignUp"))
        self.logpass.setPlaceholderText(_translate("MainWindow", "    Password"))
        self.signemail.setPlaceholderText(_translate("MainWindow", "    Enter Email-id"))
        self.signpass.setPlaceholderText(_translate("MainWindow", "    Enter Password"))
        self.signconfirmpass.setPlaceholderText(_translate("MainWindow", "    Confirm Password"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
